
version: '4.0'
services:
  app:
    image: 'eventapp2:latest'
    build:
      context: .
    container_name: eventapp2
    depends_on:
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase1'
      - 'SPRING_DATASOURCE_USERNAME=myuser1'
      - 'SPRING_DATASOURCE_PASSWORD=secret1'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
  db:
    image: 'postgres:16-alpine'
    container_name: eventdb2
    environment:
      - 'POSTGRES_DB=mydatabase1'
      - 'POSTGRES_PASSWORD=secret1'
      - 'POSTGRES_USER=myuser1'